version: '3'

services:

  ### fastapi ######################################################

  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

#    depends_on:
#      - redis-master
#      - postgres
    volumes:
      - ./:/src

  ### Postgres ################################################

#  postgres:
#    image: postgres:13.2
#    restart: unless-stopped
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_DB=postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres:/var/lib/postgresql/data
#  ### Redis Master ################################################
#
#  redis-master:
#    image: redis:6.0.9-alpine3.12
#    restart: unless-stopped
#    ports:
#      - 6379:6379

  ### nginx #######################################################
#  nginx:
#    build:
#      context: .
#      dockerfile: ./.docker/nginx/DockerFile
#    ports:
#      - 80:80
#    volumes:
#      - ./front:/var/www/html

  ### file browser #######################################################
#  filebrowser:
#    image: filebrowser/filebrowser
#    ports:
#      - 8080:80
#    volumes:
#      - ./.docker/filebrowser/.docker.json:/.filebrowser.json
#      - ./front:/srv
#      - './database.db:/database.db'
volumes:
#  postgres:
  nginx:
